<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Administrar_productos.aspx.cs" Inherits="Tienda_Wonka.Home_Admin" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<link href="http://fonts.cdnfonts.com/css/willywonka" rel="stylesheet"/>
<link rel="stylesheet" href="Wonka1.css"/>
    <title>Tienda Willy Wonka</title>
    <style type="text/css">
        .auto-style2 {
            height: 500px;
            width: 15%;
            float: left;
        }
        .auto-style3 {
            height: 500px;
            width: 85%;
            float: left;
        }
        </style>
</head>
<body>
    <form id="form1" runat="server">

     <header>
        <div class="HDiv">
            <div class="HleftDiv">
                <a href="../Inicio/Home.aspx">
                    <img src="../Imagenes/LogoWonka.png" onmouseover="this.src='../Imagenes/LogoHome.png'" onmouseout="this.src='../Imagenes/LogoWonka.png'" border="0" alt="" />
                </a>
            </div>
            <div class="HrightDiv">
                <h1>Willy Wonka&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h1>
            </div>
        </div>
    </header>
        <!-- Submenú -->
        <div class="auto-style2">
            <asp:Button ID="btnPerfil" runat="server" Height="43px" Text="Mi perfil" Width="131px" PostBackUrl="~/Usuario/Mi_perfil.aspx" />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <asp:Button ID="btnPedido" runat="server" Height="40px" Text="Pedir al proveedor" Width="131px" OnClick="btnPedido_Click" />
            <br />
            <br />
            <asp:Button ID="btnAgregarProducto" runat="server" Height="40px" Text="Agregar producto" Width="131px" OnClick="btnAgregarProducto_Click" />
            <br />
            <br />
            <br />
            <asp:Label ID="lblMensaje" runat="server" ForeColor="White"></asp:Label>
        </div>

        <!-- Cuerpo -->
        <div class="auto-style3">
            <asp:GridView ID="gvProductos" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource_lvProductos" AutoGenerateColumns="False" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2" DataKeyNames="Id_PROD" AllowPaging="True" OnRowDeleting="gvProductos_RowDeleting" OnRowEditing="gvProductos_RowEditing" OnRowUpdating="gvProductos_RowUpdating" OnRowCancelingEdit="gvProductos_RowCancelingEdit" OnDataBound="gvProductos_DataBound">
                <Columns>
                    <asp:TemplateField HeaderText="ID del producto">
                        <EditItemTemplate>
                            <asp:Label ID="edit_it_lblIdProducto" runat="server" Text='<%# Eval("Id_PROD") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="it_lblIdProducto" runat="server" Text='<%# Eval("Id_PROD") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Descripción">
                        <EditItemTemplate>
                            <asp:TextBox ID="edit_it_tbDescripcionProducto" runat="server" MaxLength="30" Text='<%# Bind("Nombre_PROD") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="it_lblDescripcionProducto" runat="server" Text='<%# Eval("Nombre_PROD") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Tipo de producto">
                        <EditItemTemplate>
                            <asp:DropDownList ID="edit_it_ddlTipoProducto" runat="server" DataSourceID="SqlDataSource_edit_it_ddlTipoProducto" DataTextField="Nombre_TP" DataValueField="Id_TP">
                            </asp:DropDownList>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="it_lblTipoProducto" runat="server" Text='<%# Eval("Nombre_TP") %>'></asp:Label>
                            <asp:Label ID="it_lblIdTipoP" runat="server" Text='<%# Eval("IdTipoP_PROD") %>' Visible="False"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio unitario">
                        <EditItemTemplate>
                            $<asp:TextBox ID="edit_it_tbPrecioProducto" runat="server" MaxLength="9" Text='<%# Bind("Precio_PROD") %>' Width="50px"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            $<asp:Label ID="it_lblPrecioProducto" runat="server" Text='<%# Eval("Precio_PROD") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Stock actual">
                        <EditItemTemplate>
                            <asp:TextBox ID="edit_it_tbStockProducto" runat="server" Text='<%# Bind("Stock_PROD") %>' TextMode="Number" Width="50px" MaxLength="5"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="it_lblStockProducto" runat="server" Text='<%# Eval("Stock_PROD") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Punto de pedido">
                        <EditItemTemplate>
                            <asp:TextBox ID="edit_it_tbPuntoPedidoProducto" runat="server" Text='<%# Bind("PuntoPedido_PROD") %>' TextMode="Number" Width="50px" MaxLength="3"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="it_lblPuntoPedidoProducto" runat="server" Text='<%# Eval("PuntoPedido_PROD") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Archivo de imagen">
                        <EditItemTemplate>
                            <asp:Label ID="edit_id_lblImageLink" runat="server" Text='<%# Eval("ImageLink_PROD") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="id_lblImageLink" runat="server" Text='<%# Eval("ImageLink_PROD") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <EmptyDataTemplate>
                    No hay productos registrados en la tienda. Diríjase a &quot;Agregar producto&quot; para registrar un nuevo producto.
                </EmptyDataTemplate>
                <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
                <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
                <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
                <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
                <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#FFF1D4" />
                <SortedAscendingHeaderStyle BackColor="#B95C30" />
                <SortedDescendingCellStyle BackColor="#F1E5CE" />
                <SortedDescendingHeaderStyle BackColor="#93451F" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource_lvProductos" runat="server" ConnectionString="<%$ ConnectionStrings:WonkaConnectionString %>" SelectCommand="SELECT [Id_PROD], [Nombre_PROD], [IdTipoP_PROD], [Precio_PROD], [Stock_PROD], [PuntoPedido_PROD], [Nombre_TP], [ImageLink_PROD]
FROM [Productos] INNER JOIN [Tipos_Producto] ON [IdTipoP_PROD] = [Id_TP]
WHERE ([Estado_PROD] = @Estado_PROD)" DeleteCommand="/**/" UpdateCommand="/**/">
                <SelectParameters>
                    <asp:Parameter DefaultValue="TRUE" Name="Estado_PROD" Type="Boolean" />
                </SelectParameters>
            </asp:SqlDataSource>
            <asp:SqlDataSource ID="SqlDataSource_edit_it_ddlTipoProducto" runat="server" ConnectionString="<%$ ConnectionStrings:WonkaConnectionString %>" SelectCommand="SELECT [Id_TP], [Nombre_TP] FROM [Tipos_Producto] WHERE ([Estado_TP] = @Estado_TP)">
                <SelectParameters>
                    <asp:Parameter DefaultValue="TRUE" Name="Estado_TP" Type="Boolean" />
                </SelectParameters>
            </asp:SqlDataSource>
            <br />
        </div>
    </form>
<footer>
    <div class="FDiv">
        <img src="../Imagenes/Fowondo.png"/>
    </div>
</footer>
</body>
</html>
